"""Authentication handling for Frank Energie integration."""
# python_frank_energie/authentication.py

import logging
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta

from .exceptions import AuthException

_LOGGER = logging.getLogger(__name__)


@dataclass(slots=True)
class Authentication:
    """Authentication data generated by the login or renewToken mutation.

    Attributes:
        authToken: The token to use for authenticated requests.
        refreshToken: The token to use to renew the authToken.
    """

    auth_token: str
    refresh_token: str
    version: str | None = None
    token_expires_at: datetime | None = None
    refresh_token_expires_at: datetime | None = None
    TOKEN_RENEWAL_MARGIN = timedelta(minutes=5)

    @staticmethod
    def from_dict(data: dict[str, object]) -> "Authentication":
        """Parse the response from the login or renewToken mutation.

        Args:
            data: The response dictionary containing token information.

        Raises:
            AuthException: If the response contains errors or is malformed.

        Returns:
            An Authentication instance with tokens.
        """
        _LOGGER.debug("Authentication response: %s", data)

        errors = data.get("errors")
        if isinstance(errors, list) and errors and isinstance(errors[0], dict):
            raise AuthException(errors[0].get("message", "Unknown authentication error"))

        inner = data.get("data")
        if not isinstance(inner, dict):
            raise AuthException("Missing 'data' in authentication response")

        payload = Authentication._extract_payload(inner)

        auth_token = payload.get("authToken") if payload else None
        refresh_token = payload.get("refreshToken") if payload else None
        if not isinstance(auth_token, str) or not isinstance(refresh_token, str):
            raise AuthException("Unexpected response: Missing or incomplete payload")

        return Authentication(auth_token=auth_token, refresh_token=refresh_token)

    @staticmethod
    def _extract_payload(
        data: dict[str, object],
    ) -> dict[str, object] | None:
        """Extract the login or renewToken payload from the unwrapped GraphQL data.

        Args:
            data: The GraphQL response's ``data`` object.

        Returns:
            The payload dict if present.
        """
        login = data.get("login")
        if isinstance(login, dict):
            return login

        renew_token = data.get("renewToken")
        if isinstance(renew_token, dict):
            return renew_token

        return None

    @property
    def is_expired(self) -> bool:
        """Return True when the token should be refreshed."""
        if self.token_expires_at is None:
            return bool(self.authToken and len(self.authToken.split(".")) >= 3)
        return datetime.now(UTC) >= (self.token_expires_at - self.TOKEN_RENEWAL_MARGIN)

    @property
    def authToken(self) -> str:
        """Backward compatibility alias."""
        return self.auth_token

    @property
    def refreshToken(self) -> str:
        """Backward compatibility alias."""
        return self.refresh_token

    def __repr__(self) -> str:
        """Hide sensitive token values."""
        return "Authentication(auth_token=***, refresh_token=***)"
