"""Authentication handling for Frank Energie integration."""
# python_frank_energie/authentication.py

import base64
import json
import logging
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta, timezone

from .exceptions import AuthException

_LOGGER = logging.getLogger(__name__)


@dataclass(slots=True)
class Authentication:
    """Authentication data generated by the login or renewToken mutation.

    Attributes:
        authToken: The token to use for authenticated requests.
        refreshToken: The token to use to renew the authToken.
    """

    auth_token: str
    refresh_token: str
    version: str | None = None
    expires_at: datetime | None = None

    @staticmethod
    def from_dict(data: dict[str, str]) -> "Authentication":
        """Parse the response from the login or renewToken mutation.

        Args:
            data: The response dictionary containing token information.

        Raises:
            AuthException: If the response contains errors or is malformed.

        Returns:
            An Authentication instance with tokens.
        """
        _LOGGER.debug("Authentication response: %s", data)

        if errors := data.get("errors"):
            raise AuthException(errors[0].get("message", "Unknown authentication error"))

        payload = Authentication._extract_payload(data)

        if not payload or "authToken" not in payload or "refreshToken" not in payload:
            raise AuthException("Unexpected response: Missing or incomplete payload")

        return Authentication(auth_token=payload["authToken"], refresh_token=payload["refreshToken"])

    @staticmethod
    def _extract_payload(
        data: dict[str, object],
    ) -> dict[str, object] | None:
        """Extract the login or renewToken payload from the response.

        Args:
            data: The full GraphQL response.

        Returns:
            The payload dict if present.
        """
        login = data.get("login")
        if isinstance(login, dict):
            return login

        renew_token = data.get("renewToken")
        if isinstance(renew_token, dict):
            return renew_token

        return None

    @property
    def is_expired(self) -> bool:
        """Return True when the token should be refreshed."""
        if self.expires_at is None:
            return True
        return datetime.now(UTC) >= (self.expires_at - timedelta(minutes=5))

    def auth_token_valid(self, tz: timezone = UTC) -> bool:
        """Check if authToken is still valid according to the expiration timestamp.

        Decodes the JWT payload via base64 (without signature verification) to
        read the ``exp`` claim.  We are a client — we do not hold the server's
        signing key and do not need to verify the signature here; the server
        validates it when the token is actually used for an API call.

        Args:
            tz: The timezone to compare against. Defaults to UTC.

        Returns:
            True if the token has not expired; otherwise, False.
        """
        try:
            # JWT is three base64url segments separated by '.'; payload is index 1
            payload_b64 = self.authToken.split(".")[1]
            # base64url uses '-' and '_'; restore padding
            payload_b64 += "=" * (4 - len(payload_b64) % 4)
            payload = json.loads(base64.urlsafe_b64decode(payload_b64))
        except Exception as err:
            _LOGGER.warning("Failed to decode authToken payload: %s", err)
            return False

        expiry = payload.get("exp")
        if not expiry:
            _LOGGER.warning("Token does not contain 'exp' field")
            return False

        return datetime.fromtimestamp(expiry, tz=UTC) > datetime.now(tz=tz)

    @property
    def authToken(self) -> str:
        """Backward compatibility alias."""
        return self.auth_token

    @property
    def refreshToken(self) -> str:
        """Backward compatibility alias."""
        return self.refresh_token

    def __repr__(self) -> str:
        """Hide sensitive token values."""
        return "Authentication(auth_token=***, refresh_token=***)"
