name: Publish to PyPI on Version Tag

on:
  push:
    tags:
      - 'v*.*.*'  # Only run when a version tag is pushed

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  build-and-publish:
    permissions:
      contents: read
      id-token: write
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    environment: pypi  # Optional but recommended for security

    strategy:
      matrix:
        python-version: ['3.13']
      fail-fast: false

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # @v2.20.0
        with:
          egress-policy: block
          allowed-endpoints: >
            fulcio.sigstore.dev:443
            tuf-repo-cdn.sigstore.dev:443
            pkg-containers.githubusercontent.com:443
            ghcr.io:443
            api.github.com:443
            github.com:443
            pypi.org:443
            files.pythonhosted.org:443
            sonarcloud.io:443
            objects.githubusercontent.com:443
            uploads.github.com:443
            upload.pypi.org:443
            test.pypi.org:443
            codecov.io:443
            uploader.codecov.io:443
            api.codecov.io:443
            cli.codecov.io:443
            storage.googleapis.com:443
            github-releases.githubusercontent.com:443
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # @v7

      # - name: List available Python versions
      #   run: pyenv install --list

      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # @v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # @v6.1.0
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip build

      - name: Build the package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # @release/v1
        with:
          repository-url: https://upload.pypi.org/legacy/  # Change to test.pypi.org for testing
          # repository-url: https://test.pypi.org/legacy/

      - name: Verify package metadata
        run: python -m pip install --upgrade twine && twine check dist/*
