name: Release Drafter

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  update_release_draft:
    permissions:
      contents: write
    name: Draft release
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # @v2.21.0
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            pypi.org:443
            files.pythonhosted.org:443
            sonarcloud.io:443
            objects.githubusercontent.com:443
            uploads.github.com:443
            upload.pypi.org:443
            test.pypi.org:443
            codecov.io:443
            uploader.codecov.io:443
            api.codecov.io:443
            cli.codecov.io:443
            storage.googleapis.com:443
            github-releases.githubusercontent.com:443
      - name: Run Release Drafter
        uses: release-drafter/release-drafter@34d80673e067bdc0c24568d3af899c216adcfaa9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
